#!/usr/bin/env python3.12
#=========================== begin_copyright_notice ============================
#
# Copyright (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
#============================ end_copyright_notice =============================

"""Generate PowerPoint report from stored TB2 benchmark results.

Usage:
    poetry run python examples/generate_report.py demo_run --output report.pptx
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Minimal report generator without full xeon_pptx.py (build incrementally)
from src.storage.sqlite_store import SQLiteResultStore
import tempfile

# Scratch root for run artifacts. gettempdir() honours TMPDIR and falls
# back to "/tmp", so this resolves to the same paths as the hardcoded
# /tmp literals it replaced while no longer pinning output to a
# world-writable directory on systems that configure TMPDIR elsewhere.
_TMP = tempfile.gettempdir()

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN
except ImportError:
    print("ERROR: python-pptx not installed. Run: pip install python-pptx", file=sys.stderr)
    sys.exit(1)


def generate_title_slide(prs, run_id: str, store: SQLiteResultStore):
    """Slide 1: Title + Summary."""
    slide = prs.slides.add_slide(prs.slide_layouts[0])  # Title slide layout

    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = "Terminal-Bench 2 Performance Analysis"

    # Query run metadata
    tasks = store.query_tasks(run_id)
    passed = sum(1 for t in tasks if t['passed'])

    subtitle_text = f"""Intel Xeon EMR Benchmark Report

Run ID: {run_id}
Tasks: {len(tasks)} total, {passed} passed
Model: gpt-4o-mini

Generated by AgentSysPerf"""

    subtitle.text = subtitle_text


def generate_summary_slide(prs, run_id: str, store: SQLiteResultStore):
    """Slide 2: Task Summary Table."""
    slide = prs.slides.add_slide(prs.slide_layouts[5])  # Blank layout

    # Title
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.5))
    title_frame = title_box.text_frame
    title_frame.text = "Task Results Summary"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(28)
    title_para.font.bold = True

    # Query data
    tasks = store.query_tasks(run_id)

    if not tasks:
        # No data message
        msg_box = slide.shapes.add_textbox(Inches(2), Inches(2), Inches(6), Inches(2))
        msg_box.text_frame.text = "No task data available for this run."
        return

    # Create table: task_id | workload | passed | duration
    rows = len(tasks) + 1  # +1 for header
    cols = 4
    left = Inches(0.5)
    top = Inches(1.2)
    width = Inches(9)
    height = Inches(0.4)

    table = slide.shapes.add_table(rows, cols, left, top, width, height * rows).table

    # Header
    headers = ["Task ID", "Workload", "Status", "Duration (s)"]
    for col_idx, header in enumerate(headers):
        cell = table.cell(0, col_idx)
        cell.text = header
        cell.text_frame.paragraphs[0].font.bold = True
        cell.text_frame.paragraphs[0].font.size = Pt(12)

    # Data rows
    for row_idx, task in enumerate(tasks, start=1):
        task_id = task['task_id'].split('/')[-1]  # Short name
        workload = task.get('workload_type', 'unknown')
        status = "✓ PASS" if task['passed'] else "✗ FAIL"
        duration = f"{task.get('duration_s', 0):.1f}" if task.get('duration_s') else "N/A"

        values = [task_id, workload, status, duration]
        for col_idx, value in enumerate(values):
            cell = table.cell(row_idx, col_idx)
            cell.text = str(value)
            cell.text_frame.paragraphs[0].font.size = Pt(11)


def generate_breakdown_slide(prs, run_id: str, store: SQLiteResultStore):
    """Slide 3: Breakdown Analysis (text summary for now)."""
    slide = prs.slides.add_slide(prs.slide_layouts[5])

    # Title
    title_box = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.5))
    title_frame = title_box.text_frame
    title_frame.text = "Breakdown Analysis"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(28)
    title_para.font.bold = True

    # Query breakdown verdicts
    verdicts = store.query_verdicts(run_id, analyzer_name='breakdown')

    if not verdicts:
        msg_box = slide.shapes.add_textbox(Inches(2), Inches(2), Inches(6), Inches(2))
        msg_box.text_frame.text = "No breakdown analysis available."
        return

    # Text summary
    content_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.2), Inches(9), Inches(4))
    tf = content_box.text_frame
    tf.word_wrap = True

    for verdict in verdicts:
        task_id = verdict['task_id'].split('/')[-1]
        verdict_text = verdict['verdict']
        evidence = json.loads(verdict['evidence'])

        # Add paragraph
        p = tf.add_paragraph()
        p.text = f"{task_id}: {verdict_text}"
        p.font.size = Pt(14)
        p.font.bold = True
        p.space_after = Pt(6)

        # Evidence details
        p2 = tf.add_paragraph()
        p2.text = (f"  Inference: {evidence.get('inference_pct', 0):.1f}%  |  "
                   f"Execution: {evidence.get('execution_pct', 0):.1f}%  |  "
                   f"Orchestration: {evidence.get('orchestration_pct', 0):.1f}%")
        p2.font.size = Pt(12)
        p2.space_after = Pt(12)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_id", help="Run identifier from benchmark")
    parser.add_argument("--output", default="tb2_report.pptx", help="Output PowerPoint file")
    parser.add_argument("--db-dir", default=f"{_TMP}/agentsysperf_tb2_simple", help="Directory with agentsysperf_results.db")
    args = parser.parse_args()

    db_dir = Path(args.db_dir)
    if not (db_dir / "agentsysperf_results.db").exists():
        print(f"ERROR: Database not found at {db_dir}/agentsysperf_results.db", file=sys.stderr)
        return 1

    print(f"=== Generating Report ===")
    print(f"Run ID: {args.run_id}")
    print(f"Database: {db_dir}/agentsysperf_results.db")
    print(f"Output: {args.output}\n")

    # Initialize store
    store = SQLiteResultStore(output_dir=db_dir)

    # Create presentation
    prs = Presentation()
    prs.slide_width = Inches(10)  # 16:9 aspect ratio
    prs.slide_height = Inches(5.625)

    print("1. Generating slides...")
    generate_title_slide(prs, args.run_id, store)
    generate_summary_slide(prs, args.run_id, store)
    generate_breakdown_slide(prs, args.run_id, store)

    # Save
    output_path = Path(args.output)
    prs.save(output_path)

    print(f"\n✓ Report generated: {output_path}")
    print(f"   Slides: {len(prs.slides)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
